# Generated by Django 5.1.2 on 2024-10-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_bill_user_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_confirm_password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_password',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
