# Generated by Django 5.1.2 on 2024-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bill_user_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='bill',
            name='price_per_item',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
