# Generated by Django 5.1.2 on 2024-10-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_student_stu_confirm_password_bill_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='student',
        ),
    ]
