# Generated by Django 5.1.2 on 2024-10-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
